### PR TITLE
Made RAM size check work on boot2docker

### PR DESCRIPTION
**Pull request by pennachin**
@AmeBel I've tested this on Mac and Ubuntu, but it won't hurt for you to test before merging as well.

### CODE REVIEW

**Comment by pennachin** [comment]
Now that I look at this more carefully, I don't think these settings should be used for a dev config. They seem to be targeted at a production server dedicated to Postgres. The Postgres wiki where these numbers come from suggests something similar. There's a lot of RAM being allocated to caching, which surely helps performance but would probably cause constant paging to disk on a busy developer machine, no?

**Comment by AmeBel** [comment]
I guess it will. I could add an environment variable for tuning the percentage.

**Comment by AmeBel** [comment]
All good on ubuntu 14.04. Thanks

**Comment by pennachin** [comment]
I guess a dev vs production environment variable makes sense, this won't be the only case where we'll want to handle things differently...

**Pull request merged**
