### PR TITLE
fix up install so that python runs and Sophia head is loaded

### PR DESCRIPTION
**Pull request by mwigzell**
the pi_vision component of 'eva-ros' docker is working. (webcam comes up, blender with Sophia head comes up).

### CODE REVIEW

**Comment by mwigzell** [comment]
it seems I can't write the pull request to the opencog/docker repo? (my enlistment is still using my forked repo, I'll change that after this, if I get access)

**Review by linas — APPROVED** [review]
I'm going to merge this, but I think it pretty important/urgent to avoid calling anything "sophia".

**Comment by linas** [comment]
> it seems I can't write the pull request to the opencog/docker repo? 

I think you mean "can't write branches to the opencog repo".  You wrote the pull req just fine.

> (my enlistment is still using my forked repo, I'll change that after this, if I get access)

No. As a general rule, you should continue working in your own repo, and then create pull reqs into the opencog repo. (Even when you have write permissions) That's the standard procedure; that's kind of the whole point of having git, as otherwise we descend to the bad-old days of using svn-style development.

**Comment by mwigzell** [comment]
ah ok. I didn't understand. So, I will make forks of any repo I intend to
update, and submit pull requests to update.

**Comment by mwigzell** [comment]
About "sophia": I see. But the issue is there is this file :
https://github.com/opencog/blender_api/blob/master/Sophia.blend
And this folder: https://github.com/opencog/robots_config/tree/master/sophia
So the original Eva.blend used to be where Sophia.blend is now. And the
sophia folder was created by someone a while ago to target the Sophia head
I thought. So I now support the startup via eva-ros/scripts/sophia.sh and
I'm not sure what to do with eva-ros/scripts/eva.sh, since it would appear
that Eva.blend is not as good? I'm confused.

**Comment by linas** [comment]
Ah. The rename to "Sophia" should not have been done in the public git repo. The issue was that, just as we were touring the robot, the Hollywood Movie "Ex Machina" came out, where the main character was a robot called Eva, ... who ... even looked like Eva, with the clear-plastic skull & everything. (This may have been intentional? David was pretty famous by then.) So there was a scramble to change the name to Sophia ... in the private git repos. Apparently, in the heat of the moment, a public git repo was renamed as well.

The right thing to do is to rename everything back to Eva. I guess maybe I should do the renaming. As to which blender file to use ... Can you tell me which one you think is the best one, and which one seems to be the second best?  (Do both have the missing nose-bone; do both have the cyclic dependencies? Any of them have lighting issues? It is possible that the nose bone was broken during an attempt to decouple the smile animations from the phoneme animations: weird stuff happened if you tried to make her talk while smiling at the same time... So I want to keep around all versions of the blend file, until we can figure out which is the "best".)

**Comment by mwigzell** [comment]
Hi LInas, so first off, I ended up with just the "blender_api" master from
github, and my search resulted in:
https://github.com/vytasrgl/blender_api.git
(In there is an Eva.blend). So I have two heads.
Let me note that the two heads I have are distinctly different: the
"Sophia.blend" has no eyes. Since she is in the blender_api master, I've
been using her, thinking that that is surely the latest. However I am using
the start up script that is in eva-ros/scripts/eva.sh. This script tries to
run from "robots_config".
I need to talk to you about that. But first.
The vytasrgl head shows following log when started on its Eva.blend:

***@***.***:blender_api2$ blender Eva.blend
Read blend: /home/mark/Dev/src/blender_api2/Eva.blend
scripts disabled for "/home/mark/Dev/src/blender_api2/Eva.blend", skipping
'loader.py'
add_relation(Bone Parent) - Could not find op_from (ComponentKey(OBdeform,
BONE, 'Nose'))
add_relation(Bone Parent) - Failed, but op_to
(ComponentKey(OBWGT-eyelid_U.R.001, TRANSFORM)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Action) - Could not find op_from (OperationKey(type: BONE,
component name: 'CYC-sleep', operation code: BONE_DONE))
add_relation(Action) - Failed, but op_to (OperationKey(type: BONE,
component name: 'eye_L', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Action) - Could not find op_from (OperationKey(type: BONE,
component name: 'CYC-normal', operation code: BONE_DONE))
add_relation(Action) - Failed, but op_to (OperationKey(type: BONE,
component name: 'eye_L', operation code: BONE_CONSTRAINTS)) was ok
WARN (bke.object): source/blender/blenkernel/intern/object.cc:3408
ob_parbone: Parent Bone: 'Nose' for Object: 'WGT-eyelid_U.R.001' doesn't
exist
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:3594
BKE_animsys_eval_driver: invalid driver -
pose.bones["blink_duration"]["prop"][0]
Read blend: /home/mark/Dev/src/blender_api2/Eva.blend
/home/mark/Dev/src/blender_api2/Eva.blend/loader.py:4: DeprecationWarning:
the imp module is deprecated in favour of importlib and slated for removal
in Python 3.12; see the module's documentation for alternative uses
register_class(...):
Warning: 'BLRigControl' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'BLRigConsole' does not contain '_PT_' with prefix and suffix
Starting AnimationManager singleton
add_relation(Bone Parent) - Could not find op_from (ComponentKey(OBdeform,
BONE, 'Nose'))
add_relation(Bone Parent) - Failed, but op_to
(ComponentKey(OBWGT-eyelid_U.R.001, TRANSFORM)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Action) - Could not find op_from (OperationKey(type: BONE,
component name: 'CYC-sleep', operation code: BONE_DONE))
add_relation(Action) - Failed, but op_to (OperationKey(type: BONE,
component name: 'eye_L', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Action) - Could not find op_from (OperationKey(type: BONE,
component name: 'CYC-normal', operation code: BONE_DONE))
add_relation(Action) - Failed, but op_to (OperationKey(type: BONE,
component name: 'eye_L', operation code: BONE_CONSTRAINTS)) was ok
WARN (bke.object): source/blender/blenkernel/intern/object.cc:3408
ob_parbone: Parent Bone: 'Nose' for Object: 'WGT-eyelid_U.R.001' doesn't
exist
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:3594
BKE_animsys_eval_driver: invalid driver -
pose.bones["blink_duration"]["prop"][0]

By contrast, the eyeless Sophia.blend from master shows:

***@***.***:/catkin_ws/src/blender_api# blender Sophia.blend
Warning: Falling back to the standard locale ("C")
Warning: property 'release_confirm' not found in keymap item
'OperatorProperties'
Read blend: /catkin_ws/src/blender_api/Sophia.blend
scripts disabled for "/catkin_ws/src/blender_api/Sophia.blend", skipping
'loader.py'
add_relation(Bone Parent) - Could not find op_from (ComponentKey(OBdeform,
BONE, 'Nose'))
add_relation(Bone Parent) - Failed, but op_to
(ComponentKey(OBWGT-eyelid_U.R.001, TRANSFORM)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Action) - Could not find op_from (OperationKey(type: BONE,
component name: 'CYC-sleep', operation code: BONE_DONE))
add_relation(Action) - Failed, but op_to (OperationKey(type: BONE,
component name: 'eye_L', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Action) - Could not find op_from (OperationKey(type: BONE,
component name: 'CYC-normal', operation code: BONE_DONE))
add_relation(Action) - Failed, but op_to (OperationKey(type: BONE,
component name: 'eye_L', operation code: BONE_CONSTRAINTS)) was ok
Dependency cycle detected:
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() depends on
  MASkin/Shading Component/MATERIAL_UPDATE() via 'Material -> Node'
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() via 'Material's
NTree'
Dependency cycle detected:
  MASkin.Scatter/Shading Component/MATERIAL_UPDATE() depends on
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() via 'Material's
NTree'
  MASkin/Shading Component/MATERIAL_UPDATE() via 'Material -> Node'
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() via 'Material's
NTree'
  MASkin.Scatter/Shading Component/MATERIAL_UPDATE() via 'Material -> Node'
Dependency cycle detected:
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() depends on
  MASkin.SSS/Shading Component/MATERIAL_UPDATE() via 'Material -> Node'
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() via 'Material's
NTree'
Dependency cycle detected:
  OBdeform/head/BONE_CONSTRAINTS() depends on
  OBcontrol/head_target/BONE_DONE() via 'Child Of'
  OBcontrol/head_target/BONE_READY() via 'Ready -> Done'
  OBcontrol/head_target/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBdeform/DEF-head/BONE_DONE() via 'Locked Track'
  OBdeform/DEF-head/BONE_READY() via 'Ready -> Done'
  OBdeform/DEF-head/BONE_POSE_PARENT() via 'Pose -> Ready'
  OBdeform/head-target/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBdeform/head-target/BONE_READY() via 'Ready -> Done'
  OBdeform/head-target/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBdeform/head/BONE_DONE() via 'Locked Track'
  OBdeform/head/BONE_READY() via 'Ready -> Done'
  OBdeform/head/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Detected 4 dependency cycles
ERROR (bke.object):
/build/blender-RL3axj/blender-2.82.a+dfsg/source/blender/blenkernel/intern/object.c:2298
ob_parbone: Object WGT-eyelid_U.R.001 with Bone parent: bone Nose doesn't
exist
ERROR (bke.anim_sys):
/build/blender-RL3axj/blender-2.82.a+dfsg/source/blender/blenkernel/intern/anim_sys.c:4160
BKE_animsys_eval_driver: invalid driver -
pose.bones["blink_duration"]["prop"][0]
Writing userprefs: '/root/.config/blender/2.82/config/userpref.blend' ok
Read blend: /catkin_ws/src/blender_api/Sophia.blend
/catkin_ws/src/blender_api/Sophia.blend/loader.py:4: DeprecationWarning:
the imp module is deprecated in favour of importlib; see the module's
documentation for alternative uses
Warning: class EVA_OT_debug contains a property which should be an
annotation!
/catkin_ws/src/blender_api/rigControl/blenderPlayback.py:267
    assign as a type annotation: EVA_OT_debug.action
Registering panel class: 'BLRigControl' misses category, please update the
script
register_class(...):
Warning: 'BLRigControl' doesn't contain '_PT_' with prefix & suffix
Registering panel class: 'BLRigConsole' misses category, please update the
script
register_class(...):
Warning: 'BLRigConsole' doesn't contain '_PT_' with prefix & suffix
Registering panel class: 'BLActuatorControl' misses category, please update
the script
register_class(...):
Warning: 'BLActuatorControl' doesn't contain '_PT_' with prefix & suffix
Warning: class HR_ACT_Blink_randomly contains a property which should be an
annotation!
/catkin_ws/src/blender_api/rigControl/actuators.py:116
    assign as a type annotation: HR_ACT_Blink_randomly.parameter_order
Traceback (most recent call last):
  File "/catkin_ws/src/blender_api/Sophia.blend/loader.py", line 15, in
<module>
    register()
  File "/catkin_ws/src/blender_api/Sophia.blend/loader.py", line 13, in
register
    rigControl.init()
  File "/catkin_ws/src/blender_api/rigControl/__init__.py", line 47, in init
    animationManager.init()
  File "/catkin_ws/src/blender_api/rigControl/animationManager.py", line
617, in init
    bpy.evaAnimationManager = AnimationManager()
  File "/catkin_ws/src/blender_api/rigControl/animationManager.py", line
81, in __init__
    self.actuatorManager = ActuatorManager()
  File "/catkin_ws/src/blender_api/rigControl/actuators.py", line 94, in
__init__
    actuator.generator.send(None)
  File "/catkin_ws/src/blender_api/artistic/actuators.py", line 28, in
blink_randomly
    self.add_parameter(bpy.props.StringProperty(name='interval',
  File "/catkin_ws/src/blender_api/rigControl/actuators.py", line 65, in
add_parameter
    getter, setter = self.register_parameter(self.name, bl_prop)
  File "/catkin_ws/src/blender_api/rigControl/actuators.py", line 129, in
register_parameter
    bltype_act = getattr(bpy.types,
'HR_ACT_{}'.format(actuator_name.capitalize()))
AttributeError: 'RNA_Types' object has no attribute 'HR_ACT_Blink_randomly'
add_relation(Bone Parent) - Could not find op_from (ComponentKey(OBdeform,
BONE, 'Nose'))
add_relation(Bone Parent) - Failed, but op_to
(ComponentKey(OBWGT-eyelid_U.R.001, TRANSFORM)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Action) - Could not find op_from (OperationKey(type: BONE,
component name: 'CYC-sleep', operation code: BONE_DONE))
add_relation(Action) - Failed, but op_to (OperationKey(type: BONE,
component name: 'eye_L', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Action) - Could not find op_from (OperationKey(type: BONE,
component name: 'CYC-normal', operation code: BONE_DONE))
add_relation(Action) - Failed, but op_to (OperationKey(type: BONE,
component name: 'eye_L', operation code: BONE_CONSTRAINTS)) was ok
Dependency cycle detected:
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() depends on
  MASkin/Shading Component/MATERIAL_UPDATE() via 'Material -> Node'
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() via 'Material's
NTree'
Dependency cycle detected:
  MASkin.Scatter/Shading Component/MATERIAL_UPDATE() depends on
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() via 'Material's
NTree'
  MASkin/Shading Component/MATERIAL_UPDATE() via 'Material -> Node'
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() via 'Material's
NTree'
  MASkin.Scatter/Shading Component/MATERIAL_UPDATE() via 'Material -> Node'
Dependency cycle detected:
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() depends on
  MASkin.SSS/Shading Component/MATERIAL_UPDATE() via 'Material -> Node'
  NTShader Nodetree/Shading Component/MATERIAL_UPDATE() via 'Material's
NTree'
Dependency cycle detected:
  OBdeform/head/BONE_CONSTRAINTS() depends on
  OBcontrol/head_target/BONE_DONE() via 'Child Of'
  OBcontrol/head_target/BONE_READY() via 'Ready -> Done'
  OBcontrol/head_target/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBdeform/DEF-head/BONE_DONE() via 'Locked Track'
  OBdeform/DEF-head/BONE_READY() via 'Ready -> Done'
  OBdeform/DEF-head/BONE_POSE_PARENT() via 'Pose -> Ready'
  OBdeform/head-target/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBdeform/head-target/BONE_READY() via 'Ready -> Done'
  OBdeform/head-target/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBdeform/head/BONE_DONE() via 'Locked Track'
  OBdeform/head/BONE_READY() via 'Ready -> Done'
  OBdeform/head/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Detected 4 dependency cycles
ERROR (bke.object):
/build/blender-RL3axj/blender-2.82.a+dfsg/source/blender/blenkernel/intern/object.c:2298
ob_parbone: Object WGT-eyelid_U.R.001 with Bone parent: bone Nose doesn't
exist
ERROR (bke.anim_sys):
/build/blender-RL3axj/blender-2.82.a+dfsg/source/blender/blenkernel/intern/anim_sys.c:4160
BKE_animsys_eval_driver: invalid driver -
pose.bones["blink_duration"]["prop"][0]

Obviously, a lot more output for the Sophia one: I suspect Sophia has more
messages/commands/bones than the Eva one? I don't know. They both have
issues with "BONE_DONE"

AHEM: regarding the "robots_config" issue I mentioned above: the perception
node which is launched thusly:
"tmux new-window -n 'geo' 'roslaunch robots_config geometry.launch
gui:=false; $SHELL'"
is seemingly not only bit-rotted but is apparently mis-aligned regarding
the "launch" arguments: The ones used in particular look like this:
"<arg name="pololu_joints" default="Eyes_Pitch;Eye_L;Eye_R" />"
whereas a launch file of same name perception/launch/geometry.launch has
the args:
"<arg name="pau_joints"
default="Eyes_Pitch;Eye_L;Eye_R;roll_base_joint;pitch_base_joint;yaw_joint;roll_neck_joint;pitch_neck_joint"
/>"
(note: there are 8 defined, but the script only has a switch for 6 of them.)
In trying to fix the perception python script "joint_state_publisher.py",
after updating for the new python syntax and commenting out a reference to
subscribing for the dynamixel joints, it actually started to run! Here, I
was running the local geometry.launch, which defines the "pau_joints". If I
use the configured geometry.launch then it fails because it hasn't matched
anything, and the code is badly written for that edge case.
In addition to this, the second python script (faces_tf2_broadcaster.py)
exits because it is timing out waiting for the camera FACES messages to
arrive:
"No camera transforms!"
I was hoping, that it is trying to read the FACES messages that my recent
changes to pi_vision should now be supplying. But it doesn't give much time
for them to start showing up, it seems like 3 seconds is the timeout. Am I
interpreting this correctly? That means I need to start up the webcam
pretty quickly. Also this file
has code that is commented out, that pertains to the "tf2" version. But as
near as I can see this code IS the tf2 version, so I am confused.
Is there any hope of engaging the original authors of the perception node?
All these issues are pretty demoralizing: I get the feeling the code in the
repos was not in running condition when it was abandoned. Do we have tags
on the repos for when the code actually did work?

**Comment by linas** [comment]
Hi Mark,

> All these issues are pretty demoralizing: I get the feeling the code in the
> repos was not in running condition when it was abandoned.

Remember what I said about herding cats and pushing rope? This is what happens when everyone has commit privileges, everyone is being pushed to work as fast as possible, and no one is in charge.  So everyone commits their favorite hack that makes things work for them, in their special the-house-is-burning-down situation, with no regard for stability. When everything is an emergency, its just chaotic.

So a list of recommendations, from the obvious to the more confusing:
1. Rename `Sophia.blend` to `eva-eyeless.blend`
2. Contact the blender mailing list about the missing nose bone.  Just write something like "I have no clue what I'm doing, I have a file with a missing bone, can you help me?"  Fingers crossed, someone will help with that.
3. I'll poke around with blender, see if I get lucky.
4. Stub out everything related to `pololu`. This is the name brand of a certain motor, and we are not driving any motors, so those links can be severed.
5. See if you can find what code is printing "No camera transforms!" -- I'm wondering if this is blender code, not tf2 code?
6. It should not matter if the camera code is getting set up late. If there are no visible faces, she yawns, looks around, yawns again, and falls asleep. Here, "sleep" means she closes her eyes, but the breathing animation continues, so the head should slowly bob, like she's breathing.  The `CYC-sleep` is the "cyclical sleeping animation".  When someone appears on the camera, she'll go into `CYC-normal`, open her eyes, yawn, turn to face you and then smile.  There's a pdf in the git repo that explains the CYC and the other animations.
7. Well, what I said above is true only when everythhing is hooked up.  The CYC animations run inside blender itself; the control of which CYC animations to launch (when she sleeps, when she wakes up), all that is from opencog scripts.
8. I'll spend the evening dinking with this, see if I get lucky.

**Comment by mwigzell** [comment]
Hi Linas, well zooming into point 5 above: yes, the code for the "No camera
transforms!" is fperception/nodes/aces_tf2_broadcaster.py
See the lines:
# Wait for camera and eye transforms
        try:
            self.listener.waitForTransform('camera', 'world',
                rospy.Time(0), rospy.Duration(3))
        except Exception:
            rospy.logerr("No camera transforms!")
            exit(1)

So like I say, the local geometry.launch has the pau joints defined: <arg
name="pau_joints"
default="Eyes_Pitch;Eye_L;Eye_R;roll_base_joint;pitch_base_joint;yaw_joint;roll_neck_joint;pitch_neck_joint"
/>
but the robots_config/sophia/geometry.launch file (the one we are
configured to use), only has NO pau_joints defined at ALL
instead it defines these pololu joints: "pololu_joints"
default="Eyes_Pitch;Eye_L;Eye_R"
Therefore the configured robot is still using pololu, so its misaligned
right? I'm tempted to replace it.
Still doesn't run though because of an index error.
As to renaming, Sophia, got it. I can do that before my next checkin, but I
don't want to rename things till I have it working.
Are you suggesting that I have the blender people fix the Eyeless Hag? Will
the eyes show up if it starts up properly? I mean, are they hiding
somewhere in the configuration?

**Comment by linas** [comment]
OK, I poked around and looked at the various blender files. I believe that when the bone connections are fixed, the eyes and the eyebrows will show up. They're in the file, but disconnected. There seem to be three other problems: (1) the lighting is wrong, she's poorly lit; (2) there's a skin texture, it's missing (3) by default, a bunch of blender controls pop up. For the default view, we want all the blender menus and buttons to be hidden, blocked.

She should not look so ugly, she should look like the screenshots in the main README of this repo.  See the bright pink spot on her nose? That bright pink spot is a spotlight, it should be illuminating all of her, she should be all bright pink, instead of grey-toned. The screenshots were taken with the spotlight broken.

The root issue is that blender 2.72 was incompatible with blender 2.69, and so, back then, some of he blend files refused to even load.  Now they all load, but all of them load with errors.  I'll spend a few more hours poking, see if I can get lucky.

In any of your explorations, have you ever gotten her to come alive (start breathing?)  She's not breathing, for me.  There's also a menu of animations; have you gotten any of hem to play?  Mostly, I'll try to get her rendering, and breathing, and then check all the animations. Its all just python code; how hard can it be, eh?   

The geometry.launch file -- do whatever it takes. This is the problem with ROS - its mostly about connecting things to other things, but you have to have a good idea of what you're connecting together, and that can be confusing.

**Comment by linas** [comment]
For the ftf2 camera, either start it earlier, or change the timeout from 3 seconds to something longer.

**Comment by mwigzell** [comment]
Got it.

**Comment by mwigzell** [comment]
*have you ever gotten her to come alive (start breathing?) She's not
breathing, for me*

No! That is the issue, I can't even see how she is supposed to be. I have
no way of exploring/fixing such a broken file. The Blender app that I have
in the docker is using the absolute latest blender that runs on Ubuntu
20.04.

*This is the problem with ROS - its mostly about connecting things to other
things, but you have to have a good idea of what you're connecting
together, and that can be confusing.*

1) Thats why I'm pestering you! I'm trying to find out, how were the bits
supposed to connect together? I hate to assume that the way it is now
shipping is wrong, and backwards etc. I have no real clue. For instance: do
you agree with me that the 6 case switch in the code for the PAU joints is
actually to be fed by the 8 item list that is in the local
"geometry.launch" and not the one that is in the
robots_config/sophia/geometry.launch ?

2) Should I reasonably expect that those 6/8 joints/motors whatever will
match to the animations in the blender model?

3) let me try to sell the current Eyeless Hag to someone in the Blender
group. I'll CC you.

**Comment by mwigzell** [comment]
I read the opencog/learn/README
Very interesting read, so if I understood right, to do vision we need to
parse the image into a visual grammar made out of pair-wise features. The
actual grammar needs to be acquired through unsupervised learning and
stored in the AtomSpace?
Sounds interesting.
As to the scientists chaotic mad lab full of experiments that don't work:
hmm
I"m for more rigour.
All that work whose design was intended to be measured: should be in a nice
giant Jenkins builder off of Github. The repos in the lab should get
validated using the PR as the hook to actually build and run at least a
subset of those measurable outcomes. Automatically. The code base should be
done using the classic git pattern whereby the master is running, tested
code, and is not modified except when a development cycle is merged back
into it. That would happen only when the development was fully validated.
This way, master is always as best as it can be made. Dev is the bleeding
edge. Cut a release branch from it, iterate until it is working properly,
merge up to master, and down to the development again. rinse and repeat

Tja

**Comment by linas** [comment]
>> [Breathing]
> No! That is the issue, I can't even see how she is supposed to be.

The `CYC-normal` animation makes her breath. If you explore the blender animation menu, you will see this, and a few other CYC animations; CYC because they are cyclical and run forever. There are also a few dozen other animations for blinking, and so on, and poking at the menu should cause them to play.

> geometry.launch

I have no idea. Without reading through what the current exposed API's are, I don't know. The problem is that the API's are scattered through assorted YAML files and python files.  I didn't build this stuff; I learned it by grepping through the source code to see what's where. FWIW, there is a a ROS graph-visualizer tool; it automatically shows you what is connected to what in ROS, how many messages per second its sending, and so on. It can help understand what is going on.

> learn

Thanks!

>  Jenkins

The atomspace code has almost 200 unit tests, and they are all run automatically for each pull request.  The green (red) buttons at the top of the README files show the test status for the code that is in git. Many/most of the other git repos have unit tests, too. (including the `learn` repo).  

The Eva pipeline had no unit tests, but even if it had, everyone would have ignored them. Being test-driven is a cultural mode. A lot of leaders who are in a hurry to get someplace do not believe in stability and test-driven development.  It's like a car without brakes: "We're going to be accelerating all the way! Why would we need brakes?"  and it just gets hard to explain.

**Comment by linas** [comment]
I spent the last 3 hours in blender. The eyeballs are in there, the teeth are there, you can see them in x-ray view. The textures that should be mapped to her eyebrows, eyes and skin are showing up in the "orphan data" list (the broken-heart icon).  I could not figure out how to connect them up.

All of the animations are also in the "orphan data" list.  I did find a menu with "poses", but when I try to run them, I see a clipped error message that seems to say it doesn't want to run untrusted python code, or something like that.  I can't see the full error messages, its clipped. I could not find the error log file anywhere ...

**Comment by mwigzell** [comment]
ah, that is encouraging. Yes, I did see the "mesh" of the eye sockets and
mouth.  Maybe not all is lost, but it is going to take a "Phd thesis" to
recover it. I'm going to try loading it up in 2.79 from the link I sent
you, maybe it loads better there.

**Comment by mwigzell** [comment]
Hi Linas, I got somewhere I think, see attached file.
This is the Sophia.blend file loaded in blender 2.76 which I pulled down
from here: https://download.blender.org/release/Blender2.76/
I did this on my native ARCH because that blender won't run from within
LXC. This is frustrating. Because the rigControl is being engaged (I ran it
from within the 'blender_api' folder, and using autostart.py:
/tmp/blender-2.76b-linux-glibc211-x86_64/blender -y Sophia.blend -P
autostart.py
It has one cyclic dependency, but otherwise no complaints from blender.

read blend: /home/mark/Dev/blender_api/Sophia.blend
Dependency cycle detected:
  deform depends on control through Child Of.
  control depends on deform through Locked Track.

Unfortunately, because I don't have the ROS etc. environment on my local
ARCH it eventually finds a module it can't load:

File "/home/mark/Dev/blender_api/rigControl/CommandListener.py", line 111,
in load_cmd_sources
    import pkg_resources
ImportError: No module named 'pkg_resources'

So what do we have? An almost running head, using the current Sophia.blend
in the current blender_api repo, and loaded with blender 2.76. I had to
enable python execution by default. Where does that leave us? Well, stuck
in time. I might be able to start working up the blender versions like the
blender contact suggested, loading up the head, writing it out, bumping the
blender version, rinse and repeat. That would work as long as blender is
providing an upgrade path via their versions.
But its a long slow process.

**Comment by mwigzell** [comment]
Hey Linas!
I realized that the 2.76 blender was displaying the gesture menu on the
right.I attached a screenshot.
I was able to try out the gestures! Hey they are really good. Very
impressive I have to say. It took me a bit of prodding to get it going, I
thought that because my environment is not set up, it wouldn't do the
gestures, but hey, that is fantastic!
So I think I need to spend some time, fix the one cyclic dependency she's
got. Then see if I do the load and save thing and try and get the image up
to the latest that way. I think now that I've seen it working, it is very
worth trying to get it back. It obviously is the result of a labor of love.
I know that it is just puppeteering, but somehow I find it very important
for CHI - computer human interaction. It will foster much acceptance. Of
course, it needs to have a genuine emotional sentience behind it. I don't
believe intelligence has to be human like necessarily, but at the gut
level, it is very compelling.
I'm going to see again if I can get the 2.76 running in Docker, that would
also be a BIG step forward. The last Docker / blender combo I tried didn't
work very well, but maybe this time will yield different results.
Cheers!
--Mark

**Pull request merged**
